name: 'KMP Build iOS App'
description: 'Build and Archive iOS application'
author: 'Mifos Initiative'
branding:
  icon: 'play'
  color: 'gray-dark'
inputs:
  match_git_authorization_token:
    description: 'GitHub Personal Access Token for Fastlane Match git repo'
    required: true

  match_password:
    description: 'Fastlane Match encryption passphrase'
    required: true

runs:
  using: composite
  steps:
    - name: Configure Ruby
      uses: ruby/setup-ruby@a2bbe5b1b236842c1cb7dd11e8e3b51e0a616acc # v1.202.0
      with:
        bundler-cache: true

    - name: Install Fastlane
      shell: bash
      run: |
        gem install bundler:2.2.27
        bundle install --jobs 4 --retry 3
        bundle exec fastlane add_plugin firebase_app_distribution
        bundle exec fastlane add_plugin increment_build_number

    - name: Build iOS App
      shell: bash
      env:
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ inputs.match_git_authorization_token }}
        MATCH_PASSWORD: ${{ inputs.match_password }}
      run: bundle exec fastlane ios build_ios

    - name: Upload iOS Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-app
        retention-days: 1
        compression-level: 9
        path: '**/*.ipa'
