name: 'KMP Build iOS App'
description: 'Build and Archive iOS application'
author: 'Mifos Initiative'
branding:
  icon: 'play'
  color: 'gray-dark'

inputs:
  match_git_basic_authorization:
    description: 'Base64-encoded GitHub token used by Fastlane Match to authenticate and clone the certificates/profiles repository securely'
    required: true

  match_password:
    description: 'Encryption passphrase used by Fastlane Match to decrypt the signing certificates and provisioning profiles stored in the remote repository'
    required: true

  keychain_password:
    description: 'Password used to create and unlock a temporary keychain during the CI build, allowing codesigning without user interaction'
    required: true

runs:
  using: composite
  steps:
    - name: Configure Ruby
      uses: ruby/setup-ruby@a2bbe5b1b236842c1cb7dd11e8e3b51e0a616acc # v1.202.0
      with:
        bundler-cache: true

    - name: Install Fastlane
      shell: bash
      run: |
        gem install bundler:2.2.27
        bundle install --jobs 4 --retry 3
        bundle exec fastlane add_plugin firebase_app_distribution
        bundle exec fastlane add_plugin increment_build_number

    - name: Build iOS App
      shell: bash
      env:
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ inputs.match_git_basic_authorization }}
        MATCH_PASSWORD: ${{ inputs.match_password }}
        KEYCHAIN_PASSWORD: ${{ inputs.keychain_password }}
      run: bundle exec fastlane ios build_ios

    - name: Upload iOS Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-app
        retention-days: 1
        compression-level: 9
        path: '**/*.ipa'