name: 'KMP Build iOS App'
description: 'Build and Archive iOS application'
author: 'Mifos Initiative'
branding:
  icon: 'play'
  color: 'gray-dark'
inputs:

  match_ssh_private_key:
    description: 'SSH private key used to access the signing repository'
    required: true

  match_password:
    description: 'Encryption passphrase used by Fastlane Match to decrypt the signing certificates and provisioning profiles stored in the remote repository'
    required: true

  git_url:
    description: 'URL of the remote repository containing the signing certificates and provisioning profiles'
    required: true

  git_branch:
    description: 'Branch of the remote repository containing the signing certificates and provisioning profiles'
    required: true

  match_type:
    description: 'Specifies the type of provisioning profile to use for code signing (e.g., adhoc, appstore, development)'
    required: true

  app_identifier:
    description: 'The bundle identifier used to uniquely identify your iOS application'
    required: true

  provisioning_profile_name:
    description: 'The name of the Provisioning profile to use for code signing'
    required: true

runs:
  using: composite
  steps:
    - name: Configure Ruby
      uses: ruby/setup-ruby@a2bbe5b1b236842c1cb7dd11e8e3b51e0a616acc # v1.202.0
      with:
        bundler-cache: true

    - name: Install Fastlane
      shell: bash
      run: |
        gem install bundler:2.2.27
        bundle install --jobs 4 --retry 3

    - name: Set up SSH for Match
      shell: bash
      env:
        MATCH_SSH_PRIVATE_KEY: ${{ inputs.match_ssh_private_key }}
      run: |
        mkdir -p ~/.ssh
        echo "$MATCH_SSH_PRIVATE_KEY" | base64 --decode > ~/.ssh/match_ci_key
        chmod 600 ~/.ssh/match_ci_key
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        echo -e "Host github.com\n  IdentityFile ~/.ssh/match_ci_key\n  StrictHostKeyChecking no" >> ~/.ssh/config

    - name: Build iOS App
      shell: bash
      env:
        MATCH_PASSWORD: ${{ inputs.match_password }}
        GIT_URL: ${{ inputs.git_url }}
        GIT_BRANCH: ${{ inputs.git_branch }}
        MATCH_TYPE: ${{ inputs.match_type }}
        APP_IDENTIFIER: ${{ inputs.app_identifier }}
        PROVISIONING_PROFILE_NAME: ${{ inputs.provisioning_profile_name }}
      run: |
        bundle exec fastlane ios build_ios \
        git_private_key:~/.ssh/match_ci_key \
        match_password:"$MATCH_PASSWORD" \
        git_url:"$GIT_URL" \
        git_branch:"$GIT_BRANCH" \
        match_type:"$MATCH_TYPE" \
        app_identifier:"$APP_IDENTIFIER" \
        provisioning_profile_name:"$PROVISIONING_PROFILE_NAME"

    - name: Upload iOS Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-app
        retention-days: 1
        compression-level: 9
        path: '**/*.ipa'