name: 'KMP Build iOS App'
description: 'Build and Archive iOS application'
author: 'Mifos Initiative'
branding:
  icon: 'play'
  color: 'gray-dark'
inputs:
  match_git_basic_authorization:
    description: 'Base64-encoded GitHub token used by Fastlane Match to authenticate and clone the certificates/profiles repository securely'
    required: true

  match_password:
    description: 'Encryption passphrase used by Fastlane Match to decrypt the signing certificates and provisioning profiles stored in the remote repository'
    required: true

  match_type:
    description: 'Specifies the type of provisioning profile to use for code signing (e.g., adhoc, appstore, development)'
    required: true

  keychain_name:
    description: 'Name of the keychain used to create and unlock a temporary keychain during the CI build, allowing codesigning without user interaction'
    required: true

  keychain_password:
    description: 'Password used to create and unlock a temporary keychain during the CI build, allowing codesigning without user interaction'
    required: true

  export_method:
    description: 'Defines how the app should be packaged for distribution (e.g., ad-hoc, app-store, development)'
    required: true

  app_identifier:
    description: 'The bundle identifier used to uniquely identify your iOS application'
    required: true

  provisioning_profile_name:
    description: 'The name of the Provisioning profile to use for code signing'
    required: true

runs:
  using: composite
  steps:
    - name: Configure Ruby
      uses: ruby/setup-ruby@a2bbe5b1b236842c1cb7dd11e8e3b51e0a616acc # v1.202.0
      with:
        bundler-cache: true

    - name: Install Fastlane
      shell: bash
      run: |
        gem install bundler:2.2.27
        bundle install --jobs 4 --retry 3
        bundle exec fastlane add_plugin firebase_app_distribution
        bundle exec fastlane add_plugin increment_build_number

    - name: Build iOS App
      shell: bash
      env:
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ inputs.match_git_basic_authorization }}
        MATCH_PASSWORD: ${{ inputs.match_password }}
        KEYCHAIN_NAME: ${{ inputs.keychain_name }}
        KEYCHAIN_PASSWORD: ${{ inputs.keychain_password }}
        MATCH_TYPE: ${{ inputs.match_type }}
        EXPORT_METHOD: ${{ inputs.export_method }}
        APP_IDENTIFIER: ${{ inputs.app_identifier }}
        PROVISIONING_PROFILE_NAME: ${{ inputs.provisioning_profile_name }}
      run: |
        bundle exec fastlane ios build_ios \
        match_git_basic_authorization:${{ env.MATCH_GIT_BASIC_AUTHORIZATION }} \
        match_password:${{ env.MATCH_PASSWORD }} \
        match_type:${{ env.MATCH_TYPE }} \
        keychain_name:${{ env.KEYCHAIN_NAME }} \
        keychain_password:${{ env.KEYCHAIN_PASSWORD }} \
        export_method:${{ env.EXPORT_METHOD }} \
        app_identifier:${{ env.APP_IDENTIFIER }} \
        provisioning_profile_name:${{ env.PROVISIONING_PROFILE_NAME }}

    - name: Upload iOS Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-app
        retention-days: 1
        compression-level: 9
        path: '**/*.ipa'
